# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20161021_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.date(2016, 10, 21)),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.date(2016, 10, 21)),
        ),
    ]
