# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20161021_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='trip_joined',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='user_joining',
            new_name='user',
        ),
    ]
